CREATE TABLE IF NOT EXISTS access_requests (
    access_request_id SERIAL NOT NULL PRIMARY KEY,
    requester_user_id INT NOT NULL,
    name VARCHAR(255),
    input_channel_id VARCHAR NOT NULL,
    input_channel_name VARCHAR NOT NULL,
    role VARCHAR(255) NOT NULL,
    reason TEXT,
    review_channel_id VARCHAR(255) NOT NULL,
    review_channel_name VARCHAR(255) NOT NULL,
    state VARCHAR(64) NOT NULL CHECK (state IN ('PENDING', 'APPROVED', 'DENIED')),
    start_date TIMESTAMP,
    access_duration TIMESTAMP,
    request_ttl TIMESTAMP,
    FOREIGN KEY (requester_user_id) REFERENCES users(user_id),
    use_yn BOOLEAN NOT NULL DEFAULT TRUE,
    create_code VARCHAR(255) NOT NULL,
    create_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_code VARCHAR(255),
    update_date TIMESTAMP,
    delete_code VARCHAR(255),
    delete_date TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0
);