CREATE TABLE IF NOT EXISTS access_policies (
    access_policy_id SERIAL NOT NULL PRIMARY KEY,
    user_id INT NOT NULL,
    input_channel_id VARCHAR NOT NULL,
    input_channel_name VARCHAR,
    title VARCHAR NOT NULL,
    reason VARCHAR NOT NULL,
    start_date TIMESTAMP NOT NULL,
    end_date TIMESTAMP NOT NULL,
    effect VARCHAR NOT NULL,
    target_channel_id VARCHAR NOT NULL,
    target_channel_name VARCHAR NOT NULL,
    target_role VARCHAR NOT NULL,
    target_role_name VARCHAR NOT NULL,
    target_slack_id VARCHAR NOT NULL,
    target_real_name VARCHAR NOT NULL,
    message_timestamp VARCHAR,
    use_yn BOOLEAN NOT NULL DEFAULT TRUE,
    create_code VARCHAR(255) NOT NULL,
    create_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_code VARCHAR(255),
    update_date TIMESTAMP,
    delete_code VARCHAR(255),
    delete_date TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0
);